var annotated_dup =
[
    [ "evo", null, [
      [ "game_lua_state", "classevo_1_1game__lua__state.html", null ],
      [ "legacy_lua_state", "classevo_1_1legacy__lua__state.html", "classevo_1_1legacy__lua__state" ],
      [ "lua_state", "classevo_1_1lua__state.html", "classevo_1_1lua__state" ],
      [ "mod_loading_lua_state", "classevo_1_1mod__loading__lua__state.html", null ]
    ] ],
    [ "Array", "class_array.html", null ],
    [ "BiomeWorldGenerator", "class_biome_world_generator.html", null ],
    [ "Class", "class_class.html", null ],
    [ "Color", "class_color.html", "class_color" ],
    [ "cs", "classcs.html", "classcs" ],
    [ "enum_wrapper", "structenum__wrapper.html", null ],
    [ "event_system", "classevent__system.html", "classevent__system" ],
    [ "FlatWorldGenerator", "class_flat_world_generator.html", null ],
    [ "Instance", "class_instance.html", null ],
    [ "LuaWorldGenerator", "class_lua_world_generator.html", null ],
    [ "Mod", "class_mod.html", "class_mod" ],
    [ "NoiseGenerator", "class_noise_generator.html", "class_noise_generator" ],
    [ "PlayerCharacter", "class_player_character.html", null ],
    [ "PlayerController", "class_player_controller.html", null ],
    [ "Prototype", "class_prototype.html", null ],
    [ "Quat", "class_quat.html", "class_quat" ],
    [ "Recipe", "class_recipe.html", null ],
    [ "StaticBlock", "class_static_block.html", "class_static_block" ],
    [ "StaticItem", "class_static_item.html", "class_static_item" ],
    [ "StaticMesh", "class_static_mesh.html", null ],
    [ "StaticMeshComponent", "class_static_mesh_component.html", "class_static_mesh_component" ],
    [ "Table", "class_table.html", null ],
    [ "Texture2D", "class_texture2_d.html", null ],
    [ "Transform", "class_transform.html", "class_transform" ],
    [ "vec2i", "classvec2i.html", "classvec2i" ],
    [ "vec3", "structvec3.html", "structvec3" ],
    [ "vec3i", "classvec3i.html", "classvec3i" ],
    [ "WorldGenerator", "class_world_generator.html", null ]
];